[secrets]
omit_keys = [
  "VITE_FIREBASE_API_KEY",
  "VITE_FIREBASE_APP_ID",
  "VITE_FIREBASE_AUTH_DOMAIN",
  "VITE_FIREBASE_MESSAGING_SENDER_ID",
  "VITE_FIREBASE_PROJECT_ID",
  "VITE_FIREBASE_VAPID_KEY",
  "VITE_IMGBB_API_KEY",
  "VITE_IMGBB_UPLOAD_URL"
]
